### ISSUE TITLE
Migrate from Heroku to K8S

### ISSUE THREAD

**Issue by jasonkuhrt** [littlebits/www-developers#25]
We should standardize on our core patterns.

**Comment by jasonkuhrt** [comment]
@stresslimit Please delete the production `www-developers` on Heroku. I cannot do it:

<img width="1156" alt="screen shot 2015-11-23 at 3 26 21 pm" src="https://cloud.githubusercontent.com/assets/284476/11348797/a2aab588-91f6-11e5-9762-4c26a1f91050.png">

**Comment by stresslimit** [comment]
Killed.
