### ISSUE TITLE
Fix dependency on private repo

### ISSUE THREAD

**Issue by jasonkuhrt** [littlebits/www-developers#27]
[We are currently leaking a Github access token publicly to download a font repo into the project](https://github.com/littlebits/www-developers/blob/master/package.json#L15). The font repo is private for licensing reasons... This situation is broken from a security standpoint and apparently Github actually automatically revokes these leaked tokens:

> We noticed that a valid OAuth access token of yours was committed to a public GitHub repository. Publicly disclosing a valid access token would allow other people to interact with GitHub on your behalf, potentially altering data, your contact information, and billing data.
> 
> As a precautionary measure, we have revoked the OAuth token. A new token will need to be generated in order to continue using OAuth to authenticate to GitHub. Here are a couple of steps you can do to ensure your account security has not been compromised:

So what to do?
1. Update to use [private NPM package](https://www.npmjs.com/package/@littlebits/asset-font-futura-round). But then contributors cannot easily work on the project because e.g. `npm` install will break for them. In practice this will not be an issue for us but I don't believe this direction is really a full solution. Its just better than the current one.
2. Put the fonts on a public bucket hosting service like S3 or GCS. Suggest by @stresslimit. At this point its as technologically public as a public Github repo or NPM module, just socially more obscure e.g. access isn't part of NPM or Github search etc.
3. Create open-source NPM module. State that you need to have bought the font to use the package....
4. Talk to the font owner for a reasonable arrangement...
5. Use open-source fonts only. There are a lot of great ones out there. But then we're "off brand".

I guess 1 is the best solution. CC @sch Do you have `0.02`?

**Comment by jasonkuhrt** [comment]
If we put `@littlebits/asset-font-futura-round` into [`optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies) then we will not block people from contributing. It think we should go with this solution as it is almost complete.

**Comment by stresslimit** [comment]
@jasonkuhrt perfect
